print("¡Hola! Por favor, ingrese la siguiente información. \n")
nombre = str(input("1.- Nombre(s) :"))
apellido = str(input("\n 2.- Apellido(S) :"))
seccion = str(input("\n 3.- Código de la asignatura y sección :"))
sede = str(input("\n 4.- Sede :"))
print("\n ¡Gracias! \n A continuación, un resumen de los datos proporcionados")
print("\n Nombre(s) y apellido(s) :", nombre, apellido)
print("\n Asignatura y sección :", seccion)
print("\n Sede :", sede)